portail_captif/urls.py
# -*- mode: python; coding: utf-8 -*-
# SPDX-License-Identifier: GPL-2.0-or-later

from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView
from django_prometheus import exports

urlpatterns = [
    url(r'^', include('users.urls')),

    # Prometheus metrics
    url(r'^metrics$', exports.ExportToDjangoView,
        name='prometheus-django-metrics'),

    # Make Android detects that is it a captive portal
    url(r'^generate_204$', RedirectView.as_view(url='/')),

    # Include Django Contrib and Core routers
    # admin/login/ is redirected to the non-admin login page
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/profile/',
        RedirectView.as_view(pattern_name='users:index')),
    url(r'^admin/login/', RedirectView.as_view(pattern_name='login')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls),
]

users/urls.py
# -*- mode: python; coding: utf-8 -*-
# SPDX-License-Identifier: GPL-2.0-or-later

from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^new_user/$', views.new_user, name='new-user'),
    url(r'^capture/$', views.capture, name='capture'),
    url(r'^edit_info/(?P<userid>[0-9]+)$', views.edit_info, name='edit-info'),
    url(r'^process/(?P<token>[a-z0-9]{32})/$', views.process, name='process'),
    url(r'^reset_password/$', views.reset_password, name='reset-password'),
]

users/models.py
# -*- mode: python; coding: utf-8 -*-
# SPDX-License-Identifier: GPL-2.0-or-later

import datetime
import uuid

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.contrib.auth.models import UserManager as DjangoUserManager
from django.db import models
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from django_prometheus.models import ExportModelOperationsMixin
from macaddress.fields import MACAddressField

from portail_captif.settings import GENERIC_IPSET_COMMAND, IPSET_NAME, \
    REQ_EXPIRE_HRS
from .tools import apply


class UserManager(DjangoUserManager):
    def create_user(self, username, email=None, password=None, **extra_fields):
        """
        Creates and saves an user
        """
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(username, email, password, **extra_fields)

    def create_superuser(self, username, email, password, **extra_fields):
        """
        Creates and saves a superuser
        """
        extra_fields.setdefault('is_superuser', True)
        return self._create_user(username, email, password, **extra_fields)


class User(ExportModelOperationsMixin('user'), PermissionsMixin,
           AbstractBaseUser):
    STATE_ACTIVE = 0
    STATE_DISABLED = 1
    STATE_ARCHIVE = 2
    STATES = (
        (0, 'STATE_ACTIVE'),
        (1, 'STATE_DISABLED'),
        (2, 'STATE_ARCHIVE'),
    )

    username = models.CharField(
        _('username'),
        max_length=150,
        unique=True,
        help_text=_(
            'Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=30, blank=True)
    email = models.EmailField(_('email address'), blank=True)
    state = models.IntegerField(choices=STATES, default=STATE_ACTIVE)
    comment = models.CharField(help_text="Commentaire, promo", max_length=255,
                               blank=True)
    registered = models.DateTimeField(auto_now_add=True)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'email']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    @property
    def is_active(self):
        return self.state == self.STATE_ACTIVE

    @property
    def is_staff(self):
        return self.is_superuser

    def get_full_name(self):
        return '%s %s' % (self.first_name, self.last_name)

    def get_short_name(self):
        return self.first_name


class Machine(ExportModelOperationsMixin('machine'), models.Model):
    proprio = models.ForeignKey('User', on_delete=models.PROTECT)
    mac_address = MACAddressField(integer=False, unique=True)

    def add_to_set(self):
        command_to_execute = ["sudo", "-n"] + GENERIC_IPSET_COMMAND.split() + [
            "add", IPSET_NAME, str(self.mac_address)]
        apply(command_to_execute)

    def del_to_set(self):
        command_to_execute = ["sudo", "-n"] + GENERIC_IPSET_COMMAND.split() + [
            "del", IPSET_NAME, str(self.mac_address)]
        apply(command_to_execute)


@receiver(post_save, sender=Machine)
def machine_post_save(**kwargs):
    machine = kwargs['instance']
    machine.add_to_set()


@receiver(post_delete, sender=Machine)
def machine_post_delete(**kwargs):
    machine = kwargs['instance']
    machine.del_to_set()


class Request(models.Model):
    PASSWD = 'PW'
    EMAIL = 'EM'
    TYPE_CHOICES = (
        (PASSWD, 'Mot de passe'),
        (EMAIL, 'Email'),
    )
    type = models.CharField(max_length=2, choices=TYPE_CHOICES)
    token = models.CharField(max_length=32)
    user = models.ForeignKey('User', on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    expires_at = models.DateTimeField()

    def save(self, **kwargs):
        if not self.expires_at:
            self.expires_at = timezone.now() \
                              + datetime.timedelta(hours=REQ_EXPIRE_HRS)
        if not self.token:
            self.token = str(uuid.uuid4()).replace('-', '')  # remove hyphens
        super().save(**kwargs)

users/forms.py
# -*- mode: python; coding: utf-8 -*-
# SPDX-License-Identifier: GPL-2.0-or-later

from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.core.validators import MinLengthValidator
from django.forms import ModelForm

from .models import User


class PassForm(forms.Form):
    passwd1 = forms.CharField(
        label=u'Nouveau mot de passe', max_length=255,
        validators=[MinLengthValidator(8)],
        widget=forms.PasswordInput,
    )
    passwd2 = forms.CharField(
        label=u'Saisir à nouveau le mot de passe',
        max_length=255,
        validators=[MinLengthValidator(8)],
        widget=forms.PasswordInput,
    )


class UserCreationAdminForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(
        label='Password', widget=forms.PasswordInput,
        validators=[MinLengthValidator(8)],
        max_length=255,
    )
    password2 = forms.CharField(
        label='Password confirmation',
        widget=forms.PasswordInput,
        validators=[MinLengthValidator(8)],
        max_length=255,
    )
    is_superuser = forms.BooleanField(label='is superuser')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.save()
        user.is_superuser = self.cleaned_data.get("is_superuser")
        return user


class UserAdminForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()
    is_superuser = forms.BooleanField(label='is superuser', required=False)

    class Meta:
        model = User
        fields = ('username', 'password', 'first_name', 'last_name', 'email')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        print("User is admin : %s" % kwargs['instance'].is_superuser)
        self.initial['is_superuser'] = kwargs['instance'].is_superuser

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.is_superuser = self.cleaned_data.get("is_superuser")
        if commit:
            user.save()
        return user


class ResetPasswordForm(forms.Form):
    username = forms.CharField(label='username', max_length=255)
    email = forms.EmailField(max_length=255)


class BaseInfoForm(ModelForm):
    class Meta:
        model = User
        fields = [
            'first_name',
            'username',
            'last_name',
            'email',
        ]
        help_texts = {
            'email': 'Le mail est utilisé pour initialiser le compte.',
        }

users/views.py
# -*- mode: python; coding: utf-8 -*-
# SPDX-License-Identifier: GPL-2.0-or-later

import ipaddress

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.signals import user_logged_in
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.db import transaction
from django.http import Http404
from django.shortcuts import get_object_or_404, render, redirect
from django.template import loader
from django.template.context_processors import csrf
from django.utils import timezone
from reversion import revisions as reversion

from portail_captif.settings import REQ_EXPIRE_STR, DEFAULT_FROM_EMAIL, \
    ASSO_NAME, ASSO_EMAIL, SITE_NAME, CAPTIVE_IP_RANGE, CAPTIVE_WIFI
from users.forms import PassForm, ResetPasswordForm, BaseInfoForm
from users.models import User, Request, Machine
from users.tools import mac_from_ip


def form(ctx, template, request):
    ctx.update(csrf(request))
    return render(request, template, ctx)


def index(request):
    """
    Show logged in user profile or index page
    """
    if request.user.is_authenticated():
        try:
            users = User.objects.get(pk=request.user.id)
        except User.DoesNotExist:
            raise Http404
        machines_list = Machine.objects.filter(proprio=users)
        return render(
            request,
            'users/profile.html',
            {
                'user': users,
                'machines_list': machines_list,
            }
        )
    else:
        return form({}, 'users/index.html', request)


def password_change_action(u_form, user, request, req=False):
    """ Fonction qui effectue le changeemnt de mdp bdd"""
    if u_form.cleaned_data['passwd1'] != u_form.cleaned_data['passwd2']:
        messages.error(request, "Les 2 mots de passe différent")
        return form({'userform': u_form}, 'users/user.html', request)
    user.set_password(u_form.cleaned_data['passwd1'])
    with transaction.atomic(), reversion.create_revision():
        user.save()
        reversion.set_comment("Réinitialisation du mot de passe")
    messages.success(request, "Le mot de passe a changé")
    if req:
        req.delete()
        return redirect("/")
    return redirect("/")


def reset_passwd_mail(req, request):
    """ Prend en argument un request, envoie un mail de réinitialisation de mot de pass """
    t = loader.get_template('users/email_passwd_request')
    c = {
        'name': str(req.user.first_name) + ' ' + str(req.user.last_name),
        'asso': ASSO_NAME,
        'asso_mail': ASSO_EMAIL,
        'site_name': SITE_NAME,
        'url': request.build_absolute_uri(
            reverse('users:process', kwargs={'token': req.token})),
        'expire_in': REQ_EXPIRE_STR,
    }
    send_mail('Votre compte %s' % SITE_NAME, t.render(c),
              DEFAULT_FROM_EMAIL, [req.user.email], fail_silently=False)
    return


def new_user(request):
    """ Vue de création d'un nouvel utilisateur, envoie un mail pour le mot de passe"""
    user = BaseInfoForm(request.POST or None)
    if user.is_valid():
        user = user.save(commit=False)
        with transaction.atomic(), reversion.create_revision():
            user.save()
            reversion.set_comment("Création")
        req = Request()
        req.type = Request.PASSWD
        req.user = user
        req.save()
        reset_passwd_mail(req, request)
        messages.success(request,
                         "L'utilisateur %s a été créé, un mail pour l'initialisation du mot de passe a été envoyé" % user.username)
        capture_mac(request, user)
        return redirect("/")
    return form({'userform': user}, 'users/user.html', request)


@login_required
def edit_info(request, userid):
    """ Edite un utilisateur à partir de son id, si l'id est différent de request.user, vérifie la possession du droit admin """
    try:
        user = User.objects.get(pk=userid)
    except User.DoesNotExist:
        messages.error(request, "Utilisateur inexistant")
        return redirect("/")
    if not request.user.is_superuser and user != request.user:
        messages.error(request,
                       "Vous ne pouvez pas modifier un autre user que vous sans droit admin")
        return redirect("/")
    user = BaseInfoForm(request.POST or None, instance=user)
    if user.is_valid():
        with transaction.atomic(), reversion.create_revision():
            user.save()
            reversion.set_user(request.user)
            reversion.set_comment("Champs modifié(s) : %s" % ', '.join(
                field for field in user.changed_data))
        messages.success(request, "L'user a bien été modifié")
        return redirect("/")
    return form({'userform': user}, 'users/user.html', request)


def get_ip(request):
    """Returns the IP of the request, accounting for the possibility of being
    behind a proxy.
    """
    ip = request.META.get("HTTP_X_FORWARDED_FOR", None)
    if ip:
        # X_FORWARDED_FOR returns client1, proxy1, proxy2,...
        ip = ip.split(", ")[0]
    else:
        ip = request.META.get("REMOTE_ADDR", "")
    return ip


def capture_mac(request, users, verbose=True):
    remote_ip = get_ip(request)
    if ipaddress.ip_address(remote_ip) in ipaddress.ip_network(
            CAPTIVE_IP_RANGE):
        mac_addr = mac_from_ip(remote_ip)
        if mac_addr:
            machine = Machine()
            machine.proprio = users
            machine.mac_address = str(mac_addr)
            try:
                with transaction.atomic(), reversion.create_revision():
                    machine.save()
                    reversion.set_comment("Enregistrement de la machine")
            except:
                if verbose:
                    messages.error(request,
                                   "Assurez-vous que la machine n'est pas déjà enregistrée")
        else:
            if verbose:
                messages.error(request, "Impossible d'enregistrer la machine")
    else:
        if verbose:
            messages.error(request,
                           "Merci de vous connecter sur le réseau du portail captif pour capturer la machine (WiFi %s)" % CAPTIVE_WIFI)


def capture_mac_afterlogin(sender, user, request, **kwargs):
    capture_mac(request, user, verbose=False)


# On récupère la mac après le login
user_logged_in.connect(capture_mac_afterlogin)


@login_required
def capture(request):
    userid = str(request.user.id)
    try:
        users = User.objects.get(pk=userid)
    except User.DoesNotExist:
        raise Http404
    capture_mac(request, users)
    return redirect("/")


def reset_password(request):
    userform = ResetPasswordForm(request.POST or None)
    if userform.is_valid():
        try:
            user = User.objects.get(username=userform.cleaned_data['username'],
                                    email=userform.cleaned_data['email'])
        except User.DoesNotExist:
            messages.error(request, "Cet utilisateur n'existe pas")
            return form({'userform': userform}, 'users/user.html', request)
        req = Request()
        req.type = Request.PASSWD
        req.user = user
        req.save()
        reset_passwd_mail(req, request)
        messages.success(request,
                         "Un mail pour l'initialisation du mot de passe a été envoyé")
        redirect("/")
    return form({'userform': userform}, 'users/user.html', request)


def process(request, token):
    valid_reqs = Request.objects.filter(expires_at__gt=timezone.now())
    req = get_object_or_404(valid_reqs, token=token)

    if req.type == Request.PASSWD:
        return process_passwd(request, req)
    else:
        messages.error(request, "Entrée incorrecte, contactez un admin")
        redirect("/")


def process_passwd(request, req):
    u_form = PassForm(request.POST or None)
    user = req.user
    if u_form.is_valid():
        return password_change_action(u_form, user, request, req=req)
    return form({'userform': u_form}, 'users/user.html', request)

users/templates/users/index.html
{% extends "base.html" %}
{% comment %}
SPDX-License-Identifier: GPL-2.0-or-later
{% endcomment %}
{# This page is shown when user is not logged in #}

{% load bootstrap3 %}
{% load staticfiles %}

{% block title %}Accueil{% endblock %}

{% block content %}
    <h1>Bienvenue à toi !</h1>

    <p class="lead">
        Ce portail mis en place par le Cr@ns te permet d'accéder gratuitement à Internet sur le campus
        durant ton passage.
    </p>

    <div class="thumbnail text-center">
        <object id="svg-object" data="{% static "/logo/crans.svg" %}" type="image/svg+xml" width="230"></object>
    </div>

    <div class="row">
        <div class="col-sm-6 col-md-6">
            <div class="col-12">
                <div class="thumbnail">
                    <div class="caption">
                        <h3>Inscription</h3>
                        <p>Si vous n'avez pas de compte, inscrivez-vous pour bénéficier d'un accès à internet !</p>
                        <p><a href="{% url 'users:new-user' %}" class="btn btn-success" role="button">Inscription</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-6">
            <div class="col-12">
                <div class="thumbnail">
                    <div class="caption">
                        <h3>Identification</h3>
                        <p>Si avez déjà un compte, identifiez-vous pour accèder à Internet.</p>
                        <p><a href="{% url 'login' %}" class="btn btn-primary" role="button">Identification</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <h2>Conditions d'utilisation</h2>
    <p>
        Compte tenu des obligations de traçabilité des connexions à internet, vous vous engagez à fournir des
        informations exactes lors de votre inscription conformément à l'article 441-1 du nouveau code pénal.
        Vous êtes seul responsable de l'utilisation du service, conformément aux articles L32 et L33 du code des postes
        et télécomunications éléctroniques.
    </p>
{% endblock %}

users/templates/users/profile.html
{% extends "base.html" %}
{% comment %}
SPDX-License-Identifier: GPL-2.0-or-later
{% endcomment %}

{% load bootstrap3 %}
{% load i18n %}

{% block title %}Profil{% endblock %}

{% block content %}
    <h2>Compte</h2>
    <div>
        <a class="btn btn-primary btn-sm" role="button" href="{% url 'users:edit-info' user.id %}">
            <i class="glyphicon glyphicon-edit"></i>
            Editer
        </a>
        <a class="btn btn-primary btn-sm" role="button" href="{% url 'password_change' %}">
            <i class="glyphicon glyphicon-lock"></i>
            Changer le mot de passe
        </a>
    </div>
    <dl class="dl-horizontal row profile-info pt4">
        <div class="col-md-6">
            <dt>{% trans "first name" as rel %}{{ rel|capfirst }}</dt>
            <dd>{{ user.first_name }}</dd>
        </div>
        <div class="col-md-6">
            <dt>{% trans "last name" as rel %}{{ rel|capfirst }}</dt>
            <dd>{{ user.last_name }}</dd>
        </div>
        <div class="col-md-6">
            <dt>{% trans "username" as rel %}{{ rel|capfirst }}</dt>
            <dd>{{ user.username }}</dd>
        </div>
        <div class="col-md-6">
            <dt>{% trans "email address" as rel %}{{ rel|capfirst }}</dt>
            <dd>{{ user.email }}</dd>
        </div>
        <div class="col-md-6">
            <dt>Commentaire</dt>
            <dd>{{ user.comment }}</dd>
        </div>
        <div class="col-md-6">
            <dt>{% trans "date joined" as rel %}{{ rel|capfirst }}</dt>
            <dd>{{ user.registered }}</dd>
        </div>
        <div class="col-md-6">
            <dt>{% trans "last login" as rel %}{{ rel|capfirst }}</dt>
            <dd>{{ user.last_login }}</dd>
        </div>
        <div class="col-md-6">
            <dt>Statut</dt>
            <dd>{% if user.state == 0 %}
                <i class="text-success">Actif</i>
            {% elif user.state == 1 %}
                <i class="text-danger">Désactivé</i>
            {% elif user.state == 2 %}
                <i class="text-warning">Archivé</i>
            {% endif %}
            </dd>
        </div>
    </dl>

    <h2>Machines enregistrées</h2>
    <a class="btn btn-primary btn-sm" role="button" href="{% url 'users:capture' %}">
        <i class="glyphicon glyphicon-flash"></i>
        Enregistrer la machine utilisée actuellement
    </a>
    <ul class="pt4">
        {% for machine in machines_list %}
            <li>{{ machine.mac_address }}</li>
            {# TODO date d'ajout #}
        {% endfor %}
    </ul>
{% endblock %}

users/templates/users/user.html
{% extends "base.html" %}
{% comment %}
SPDX-License-Identifier: GPL-2.0-or-later
{% endcomment %}

{% load bootstrap3 %}

{% block title %}Création et modification d'utilisateur{% endblock %}

{% block content %}
    {% bootstrap_form_errors userform %}

    <form class="form" method="post">
        {% csrf_token %}
        {% bootstrap_form userform %}
        {% bootstrap_button "Soumettre" button_type="submit" icon="star" %}
    </form>
{% endblock %}